

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class YoneticiEkrani extends javax.swing.JDialog {
    DefaultTableModel model1=null;
    DefaultTableModel model2=null;
    YoneticiIslemleri islemler=new YoneticiIslemleri();

    /**
     * Creates new form YoneticiEkrani
     */
    public YoneticiEkrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model1=(DefaultTableModel)uye_tablosu.getModel();
        model2=(DefaultTableModel)kitap_tablosu.getModel();
        uyeleriGoruntule();
        kitaplariGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        uye_sil = new javax.swing.JButton();
        uye_guncelle = new javax.swing.JButton();
        kitapEkle = new javax.swing.JButton();
        kitapsil = new javax.swing.JButton();
        kitapgüncelle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        uye_tablosu = new javax.swing.JTable();
        emanetkitap = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        kitap_tablosu = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        uye_mesaj_yazisi = new javax.swing.JLabel();
        tc_alani = new javax.swing.JTextField();
        uye_adi_alani = new javax.swing.JTextField();
        soyad_alani = new javax.swing.JTextField();
        email_alani = new javax.swing.JTextField();
        tel_alani = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        yayin_evi_alani = new javax.swing.JTextField();
        kitap_adi_alani = new javax.swing.JTextField();
        yazar_adi_alani = new javax.swing.JTextField();
        sayfa_sayisi_alani = new javax.swing.JTextField();
        cb_kitap_turu = new javax.swing.JComboBox<>();
        stok_alani = new javax.swing.JTextField();
        kitap_mesaj_yazisi = new javax.swing.JLabel();
        uye_arama_cubugu = new javax.swing.JTextField();
        kitap_arama_cubugu = new javax.swing.JTextField();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 102));
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Yönetici Ekranı");

        uye_sil.setText("Üye Sil");
        uye_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uye_silActionPerformed(evt);
            }
        });

        uye_guncelle.setText("Üye Güncelle");
        uye_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uye_guncelleActionPerformed(evt);
            }
        });

        kitapEkle.setText("Kitap Ekle");
        kitapEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapEkleActionPerformed(evt);
            }
        });

        kitapsil.setText("Kitap Sil");
        kitapsil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapsilActionPerformed(evt);
            }
        });

        kitapgüncelle.setText("Kitap Güncelle");
        kitapgüncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapgüncelleActionPerformed(evt);
            }
        });

        uye_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TcKimlikNo", "Ad", "Soyad", "Email", "Telefon"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        uye_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uye_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(uye_tablosu);
        if (uye_tablosu.getColumnModel().getColumnCount() > 0) {
            uye_tablosu.getColumnModel().getColumn(0).setResizable(false);
            uye_tablosu.getColumnModel().getColumn(1).setResizable(false);
            uye_tablosu.getColumnModel().getColumn(2).setResizable(false);
            uye_tablosu.getColumnModel().getColumn(3).setResizable(false);
            uye_tablosu.getColumnModel().getColumn(4).setResizable(false);
        }

        emanetkitap.setText("Emanet Kitapları Görüntüle");
        emanetkitap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emanetkitapActionPerformed(evt);
            }
        });

        kitap_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Ad", "Yazar Adı", "Yayin Evi", "Kitap Türü", "Sayfa Sayısı", "Stok"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        kitap_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kitap_tablosuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(kitap_tablosu);
        if (kitap_tablosu.getColumnModel().getColumnCount() > 0) {
            kitap_tablosu.getColumnModel().getColumn(0).setResizable(false);
            kitap_tablosu.getColumnModel().getColumn(1).setResizable(false);
            kitap_tablosu.getColumnModel().getColumn(2).setResizable(false);
            kitap_tablosu.getColumnModel().getColumn(3).setResizable(false);
            kitap_tablosu.getColumnModel().getColumn(4).setResizable(false);
            kitap_tablosu.getColumnModel().getColumn(5).setResizable(false);
            kitap_tablosu.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel2.setText("TcKimlikNo :");

        jLabel3.setText("Ad :");

        jLabel4.setText("Soyad :");

        jLabel5.setText("Email :");

        jLabel6.setText("Telefon :");

        uye_mesaj_yazisi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        uye_mesaj_yazisi.setForeground(new java.awt.Color(255, 51, 51));

        email_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_alaniActionPerformed(evt);
            }
        });

        jLabel7.setText("Yayın Evi :");

        jLabel8.setText("Kitap Adı :");

        jLabel9.setText("Yazar Adı :");

        jLabel10.setText("Kitap Türü :");

        jLabel11.setText("Sayfa Sayısı :");

        jLabel13.setText("Stok :");

        yayin_evi_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yayin_evi_alaniActionPerformed(evt);
            }
        });

        sayfa_sayisi_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sayfa_sayisi_alaniActionPerformed(evt);
            }
        });

        cb_kitap_turu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aşk", "Polisiye", "Fantastik", "Eğitim", "Dünya Klasiği", "Roman", "Psikoloji", "Gençlik", "Tarih", "Çocuk", "Gezi", "Kişisel Gelişim", "Bilim-Kurgu" }));

        kitap_mesaj_yazisi.setForeground(new java.awt.Color(255, 51, 51));

        uye_arama_cubugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uye_arama_cubuguActionPerformed(evt);
            }
        });
        uye_arama_cubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                uye_arama_cubuguKeyReleased(evt);
            }
        });

        kitap_arama_cubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kitap_arama_cubuguKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uye_mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(uye_arama_cubugu, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(uye_adi_alani)
                                                .addComponent(soyad_alani)
                                                .addComponent(email_alani)
                                                .addComponent(tel_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tc_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(36, 36, 36)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(uye_guncelle, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                        .addComponent(uye_sil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emanetkitap, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(177, 177, 177)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kitap_mesaj_yazisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(yazar_adi_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                            .addComponent(kitap_adi_alani))
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(kitapgüncelle, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                            .addComponent(kitapEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(stok_alani)
                                            .addComponent(sayfa_sayisi_alani, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cb_kitap_turu, javax.swing.GroupLayout.Alignment.LEADING, 0, 129, Short.MAX_VALUE)
                                            .addComponent(yayin_evi_alani, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(21, 21, 21)
                                        .addComponent(kitapsil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(kitap_arama_cubugu))))
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kitap_arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emanetkitap)
                            .addComponent(uye_arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kitap_adi_alani, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kitapEkle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(yazar_adi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kitapgüncelle)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(yayin_evi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kitapsil)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cb_kitap_turu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sayfa_sayisi_alani)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stok_alani)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tc_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uye_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(uye_adi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uye_sil))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(soyad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tel_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(uye_mesaj_yazisi, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                    .addComponent(kitap_mesaj_yazisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emanetkitapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emanetkitapActionPerformed
    JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
    EmanetKitapEkrani  emanetKitapEkrani = new EmanetKitapEkrani(frame,true);
    emanetKitapEkrani.setLocationRelativeTo(null);
    emanetKitapEkrani.setVisible(true);
    setVisible(true);
        
    }//GEN-LAST:event_emanetkitapActionPerformed

    private void email_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_alaniActionPerformed

    private void uye_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uye_guncelleActionPerformed
        uye_mesaj_yazisi.setText("");
        int secilirow=uye_tablosu.getSelectedRow();
        String ad=uye_adi_alani.getText();
        String soyad=soyad_alani.getText();
        String email=email_alani.getText();
        String tel=tel_alani.getText();
        if(secilirow == -1){
            if(model1.getRowCount() == 0){
                uye_mesaj_yazisi.setText("Şu anda Üye Tablosu boş..");
            }
            uye_mesaj_yazisi.setText("Lütfen Güncellenecek Üyeyi seçiniz..");
        }
        else{
            String tc=model1.getValueAt(secilirow, 0).toString();
            islemler.uyeGuncelle(tc, ad, soyad, email, tel);
            uyeleriGoruntule();
            uye_mesaj_yazisi.setText("Üye Tablosu başarıyla Güncellendi.");
            
            
        }
        
    }//GEN-LAST:event_uye_guncelleActionPerformed

    private void uye_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uye_silActionPerformed
        uye_mesaj_yazisi.setText("");
        int secilirow=uye_tablosu.getSelectedRow();
        if(secilirow == -1){
            if(model1.getRowCount() == 0){
                uye_mesaj_yazisi.setText("Şu anda Üye Tablosu boş.");
            }
            uye_mesaj_yazisi.setText("Lütfen Silinecek Üyeyi seçiniz.");
        }
        else{
            String tc=model1.getValueAt(secilirow, 0).toString();
            islemler.uyeSil(tc);
            uyeleriGoruntule();
            uye_mesaj_yazisi.setText("Üye başarıyla silindi.");
            
        }
        
    }//GEN-LAST:event_uye_silActionPerformed

    private void uye_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uye_tablosuMouseClicked
        int secilirow=uye_tablosu.getSelectedRow();
        tc_alani.setText(model1.getValueAt(secilirow, 0).toString());
        uye_adi_alani.setText(model1.getValueAt(secilirow, 1).toString());
        soyad_alani.setText(model1.getValueAt(secilirow, 2).toString());
        email_alani.setText(model1.getValueAt(secilirow, 3).toString());
        tel_alani.setText(model1.getValueAt(secilirow, 4).toString());
        
    }//GEN-LAST:event_uye_tablosuMouseClicked
    public void dinamikUyeAra(String ara){
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(model1);
        
        uye_tablosu.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    private void uye_arama_cubuguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uye_arama_cubuguActionPerformed
        
    }//GEN-LAST:event_uye_arama_cubuguActionPerformed

    private void uye_arama_cubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uye_arama_cubuguKeyReleased
        String ara=uye_arama_cubugu.getText();
        dinamikUyeAra(ara);
    }//GEN-LAST:event_uye_arama_cubuguKeyReleased

    private void sayfa_sayisi_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sayfa_sayisi_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sayfa_sayisi_alaniActionPerformed

    private void yayin_evi_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yayin_evi_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yayin_evi_alaniActionPerformed
    public void dinamikKitapAra(String ara){
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(model2);
        
        kitap_tablosu.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    private void kitap_arama_cubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kitap_arama_cubuguKeyReleased
        String ara=kitap_arama_cubugu.getText();
        dinamikKitapAra(ara);
    }//GEN-LAST:event_kitap_arama_cubuguKeyReleased

    private void kitap_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kitap_tablosuMouseClicked
        int secilirow=kitap_tablosu.getSelectedRow();
        kitap_adi_alani.setText(model2.getValueAt(secilirow, 1).toString());
        yazar_adi_alani.setText(model2.getValueAt(secilirow, 2).toString());
        yayin_evi_alani.setText(model2.getValueAt(secilirow, 3).toString());
        cb_kitap_turu.setSelectedItem(model2.getValueAt(secilirow, 4));
        sayfa_sayisi_alani.setText(model2.getValueAt(secilirow, 5).toString());
        stok_alani.setText(model2.getValueAt(secilirow, 6).toString());
        
    }//GEN-LAST:event_kitap_tablosuMouseClicked

    private void kitapEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapEkleActionPerformed
        String kitap_adi=kitap_adi_alani.getText();
        String yazar_adi=yazar_adi_alani.getText();
        String yayin_evi=yayin_evi_alani.getText();
        String kitap_turu=cb_kitap_turu.getSelectedItem().toString();
        String sayfasayisi=sayfa_sayisi_alani.getText();
        String stok=stok_alani.getText();
        if(kitap_adi.trim().equals("")||yazar_adi.trim().equals("")||yayin_evi.trim().equals("")||sayfasayisi.trim().equals("")||stok.trim().equals("")){
            kitap_mesaj_yazisi.setText("Lütfen bilgileri eksiksiz doldurun.");
        }
        else{
            islemler.kitapEkle(kitap_adi, yazar_adi, yayin_evi, kitap_turu, Integer.valueOf(sayfasayisi), Integer.valueOf(stok));
            kitaplariGoruntule();
            kitap_mesaj_yazisi.setText("Yeni Kitap başarıyla eklendi.");
        }
        
    }//GEN-LAST:event_kitapEkleActionPerformed

    private void kitapgüncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapgüncelleActionPerformed
        kitap_mesaj_yazisi.setText("");
        int secilirow=kitap_tablosu.getSelectedRow();
        String kitap_adi=kitap_adi_alani.getText();
        String yazar_adi=yazar_adi_alani.getText();
        String yayin_evi=yayin_evi_alani.getText();
        String kitap_turu=cb_kitap_turu.getSelectedItem().toString();
        String sayfasayisi=sayfa_sayisi_alani.getText();
        String stok=stok_alani.getText();
        if(secilirow == -1){
            if(model2.getRowCount() == 0){
                kitap_mesaj_yazisi.setText("Şu anda kitap tablosu boş.");
            }
            kitap_mesaj_yazisi.setText("Lütfen Güncellenecek kitabı seçin.");
            
        }
        else{
            int id=(int)model2.getValueAt(secilirow, 0);
            islemler.kitapGuncelle(id, kitap_adi, yazar_adi, yayin_evi, kitap_turu, Integer.valueOf(sayfasayisi), Integer.valueOf(stok));
            kitaplariGoruntule();
            kitap_mesaj_yazisi.setText("Kitap başarıyla güncellendi.");
        }
    }//GEN-LAST:event_kitapgüncelleActionPerformed

    private void kitapsilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapsilActionPerformed
        kitap_mesaj_yazisi.setText("");
        int secilirow=kitap_tablosu.getSelectedRow();
        if(secilirow == -1){
            if(model2.getRowCount() == 0 ){
                kitap_mesaj_yazisi.setText("Şu anda kitap tablosu boş.");
            }
            kitap_mesaj_yazisi.setText("Lütfen Silinecek kitap seçiniz.");
        }
        else{
            int id=(int)model2.getValueAt(secilirow, 0);
            String ad=kitap_adi_alani.getText();
            String stok=stok_alani.getText();
            islemler.kitapSil(id,ad,Integer.valueOf(stok));
            kitaplariGoruntule();
            kitap_mesaj_yazisi.setText("Kitap başarıyla silindi.");
        }
    }//GEN-LAST:event_kitapsilActionPerformed

    /**
     * @param args the command line arguments
     */
    public void uyeleriGoruntule(){
       model1.setRowCount(0);
        ArrayList<Uye> uye_listesi=new ArrayList<Uye>();
        uye_listesi=islemler.uyeleriGetir();
        if(uye_listesi != null){
        for(Uye uye:uye_listesi){
            Object[]eklenecek={uye.getTcKimlikNo(),uye.getAd(),uye.getSoyad(),uye.getEmail(),uye.getTelefon()};
            model1.addRow(eklenecek);
            
        }
        }
        
        
    }
    public void kitaplariGoruntule(){
        model2.setRowCount(0);
        ArrayList<Kitap> kitap_listesi=new ArrayList<Kitap>();
        kitap_listesi=islemler.kitaplariGetir();
        if(kitap_listesi != null){
            for(Kitap kitap:kitap_listesi){
                Object [] eklenecek={kitap.getId(),kitap.getAd(),kitap.getYazarAdi(),kitap.getYayinEvi(),kitap.getKitapTuru(),kitap.getSayfaSayisi(),kitap.getStok()};
                model2.addRow(eklenecek);
            }
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                YoneticiEkrani dialog = new YoneticiEkrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_kitap_turu;
    private javax.swing.JTextField email_alani;
    private javax.swing.JButton emanetkitap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kitapEkle;
    private javax.swing.JTextField kitap_adi_alani;
    private javax.swing.JTextField kitap_arama_cubugu;
    private javax.swing.JLabel kitap_mesaj_yazisi;
    private javax.swing.JTable kitap_tablosu;
    private javax.swing.JButton kitapgüncelle;
    private javax.swing.JButton kitapsil;
    private javax.swing.JTextField sayfa_sayisi_alani;
    private javax.swing.JTextField soyad_alani;
    private javax.swing.JTextField stok_alani;
    private javax.swing.JTextField tc_alani;
    private javax.swing.JTextField tel_alani;
    private javax.swing.JTextField uye_adi_alani;
    private javax.swing.JTextField uye_arama_cubugu;
    private javax.swing.JButton uye_guncelle;
    private javax.swing.JLabel uye_mesaj_yazisi;
    private javax.swing.JButton uye_sil;
    private javax.swing.JTable uye_tablosu;
    private javax.swing.JTextField yayin_evi_alani;
    private javax.swing.JTextField yazar_adi_alani;
    // End of variables declaration//GEN-END:variables
}
